### ISSUE TITLE
Multiple tests not working

### ISSUE THREAD

**Issue by schollz** [tscholl2/isitrandom#3]
Serial and frequency work on their own just fine. But they don't work together: https://github.com/tscholl2/isitrandom/commit/be74ad61ba4d6a0ef15e36b24dcca7d9fdd0f1f0

```
~/work/src/github.com/tscholl2/isitrandom/examples $ go test
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200780c0, 0x512a51, 0x12, 0x51f8f0, 0xc42003fd30)
    /usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc4200780c0)
    /usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc4200780c0, 0xc42003fe20)
    /usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x51f918, 0x6781e0, 0x5, 0x5, 0x7f6165b1a000)
    /usr/local/go/src/testing/testing.go:799 +0x2f5
testing.(*M).Run(0xc42003fee8, 0x500ba0)
    /usr/local/go/src/testing/testing.go:743 +0x85
main.main()
    github.com/tscholl2/isitrandom/examples/_test/_testmain.go:62 +0xc6

goroutine 5 [chan receive]:
testing.(*T).Run(0xc420078180, 0x5110f0, 0x9, 0xc420014840, 0x2)
    /usr/local/go/src/testing/testing.go:647 +0x316
github.com/tscholl2/isitrandom.TestRNG(0xc420078180, 0x58b340, 0xc420050070)
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:54 +0x202
github.com/tscholl2/isitrandom/examples.TestAlternatingRNG(0xc420078180)
    /home/zack/work/src/github.com/tscholl2/isitrandom/examples/alternating_test.go:27 +0x43
testing.tRunner(0xc420078180, 0x51f8f0)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 6 [chan send]:
github.com/tscholl2/isitrandom.(*channelReader).read(0xc4200105c0)
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:75 +0x125
created by github.com/tscholl2/isitrandom.readerToChannel
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:81 +0x9f

goroutine 7 [chan send]:
github.com/tscholl2/isitrandom.split.func1(0xc42005a2a0, 0x2, 0xc4200105e0)
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:92 +0xa5
created by github.com/tscholl2/isitrandom.split
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:98 +0x107

goroutine 8 [chan receive]:
github.com/tscholl2/isitrandom.buildTest.func1(0xc42005a300, 0xf1)
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:15 +0x57
github.com/tscholl2/isitrandom.TestRNG.func1(0xc420078240)
    /home/zack/work/src/github.com/tscholl2/isitrandom/main.go:50 +0x5c
testing.tRunner(0xc420078240, 0xc420014840)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL    github.com/tscholl2/isitrandom/examples 0.004s
```

**Comment by tscholl2** [comment]
Yes I realized this won't work at some point. Basically in `TestRNG` when the channel is split (`s := split(c, len(tests))`) it makes a channel for each test. However, if not all tests are being run, then one of the channels won't have anyone receiving from it. In which case everything will block.

One fix is to not use sub-tests and just run everything. It may be possible to change how the channels are split, so it only creates channels for the tests that are run. 

Or maybe we can build a "listener" that attaches to the channel when the test is run, but we can't start sending bytes down the channel until all listeners are attached, and I'm not sure how to know that.
